### ISSUE TITLE
`-w wanted_sector_size` option of `mkfs.f2fs` is ignored

### ISSUE THREAD

**Issue by sitd2813** [Sys-AI-Foundation/f2fs-tools#15]
~~I created the filesystem with `mkfs.f2fs -w 4096 DEV`, but it always prints `Info: sector size = 512`, not `Info: sector size = 4096`.~~

~~I checked the latest source code on <https://git.kernel.org/pub/scm/linux/kernel/git/jaegeuk/f2fs-tools.git/> and found 2 problems.~~

1. ~~The value passed to `-w` is assigned to `struct f2fs_configuration`'s member `c.wanted_sector_size`, but it is never used.~~

    ~~It seems that `c.sector_size` is used to create a fs of certain sector size. So, if `c.wanted_sector_size` is set, `c.sector_size` must be also set. However, `c.wanted_sector_size` is not used, so `c.sector_size` is always `DEFAULT_SECTOR_SIZE` which is 512.~~

2. ~~The position of `add_default_options()` and the parsing while loop in the function `f2fs_parse_options()` should be switched.~~

    ~~The parsing while loop parse `-w`, but after that `add_default_options()` is called and it changes a few options including `c.wanted_sector_size` to default values. This renders `-w` option useless.~~

**Comment by sitd2813** [comment]
It was my misunderstanding that `mkfs.f2fs` does not handle `-w` option correctly. `-w` option has nothing to do with filesystem's sector size and F2FS's block size is always 4 kiB according to the paper.

Sorry for the incorrect bug report.

**Comment by Vednier** [comment]
If -w option have nothing to do with sector size then what is it for? F2fs documentation isn't best.

**Comment by bezirg** [comment]
This issue should be re-opened. What is the point of -w? And how we can reliably check the sector size that f2fs uses?
