### ISSUE TITLE
[Important] Outdated repository, new upstream is at git.kernel.org

### ISSUE THREAD

**Issue by aviallon** [Sys-AI-Foundation/f2fs-tools#16]
The repository seems to have silently moved to https://git.kernel.org/pub/scm/linux/kernel/git/jaegeuk/f2fs-tools.git/

It is therefore useless to report issues here.

**Comment by Nyanraltotlapun** [comment]
> 

But where to report issue now?

**Comment by jaegeuk** [comment]
Could you please report any issue to the f2fs mailing list?
***@***.***

Thanks,

**Comment by Harvie** [comment]
https://sourceforge.net/projects/linux-f2fs/lists/linux-f2fs-devel
