### ISSUE TITLE
How to format f2fs partition to enable casefold ?

### ISSUE THREAD

**Issue by youling257** [Sys-AI-Foundation/f2fs-tools#5]
the ext4 partition, i google search found this https://www.reddit.com/r/linux_gaming/comments/cbrc7s/52_kernel_supports_caseinsensitive_directories/
mkfs -t ext4 -E encoding=utf8

but, how to format f2fs partition to enable casefold ?

**Comment by jaegeuk** [comment]
Hi,

Could you give it a try?
mkfs.f2fs -C utf8

Thanks,

2019년 12월 5일 (목) 오전 11:41, youling257 <notifications@github.com>님이 작성:

**Comment by youling257** [comment]
Thanks, mkfs.f2fs -O casefold -C utf8, casefold work.
